sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.3"
cache:
  directories:
    - $HOME/.m2

install:
  - pushd `pwd`
  - cd $HOME/build
  - if [[ -z $GFW_BRANCH ]]; then GFW_BRANCH=1.0.x; fi
  - git clone --depth=1 --branch=$GFW_BRANCH https://github.com/terasolunaorg/terasoluna-gfw.git terasolunaorg/terasoluna-gfw
  - cd terasolunaorg/terasoluna-gfw
  - sh ./mvn-build-all.sh install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
  - popd

before_script:
  - createdb terasoluna-gfw-functionaltest --locale=C --encoding=UTF8 --template=template0
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CARGO_DAEMON_WEBAPP_VERSION=1.4.16
  - mvn dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./target/.
  - java -jar ./target/cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script:
  - mvn -U install -f terasoluna-gfw-functionaltest-parent/pom.xml -Dorg.springframework-version=3.2.15.RELEASE
  - mvn -U sql:execute -f terasoluna-gfw-functionaltest-initdb/pom.xml -Dorg.springframework-version=3.2.15.RELEASE
  - mvn -U install -f terasoluna-gfw-functionaltest-env/pom.xml -P tomcat8-postgresql -Dorg.springframework-version=3.2.15.RELEASE
  - mvn -U install -f terasoluna-gfw-functionaltest-domain/pom.xml -Dorg.springframework-version=3.2.15.RELEASE
  - mvn -U install cargo:daemon-start -f terasoluna-gfw-functionaltest-web/pom.xml -P warpack-env,travis -Dorg.springframework-version=3.2.15.RELEASE
  - mvn -U test -f terasoluna-gfw-functionaltest-selenium/pom.xml -Dorg.springframework-version=3.2.15.RELEASE
