language: java
jdk:
  - oraclejdk8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CARGO_DAEMON_WEBAPP_VERSION=1.4.16
  - mvn dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./target/.
  - java -jar ./target/cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script:
  - mvn install -f terasoluna-gfw-functionaltest-parent/pom.xml
  - mvn install -f terasoluna-gfw-functionaltest-env/pom.xml
  - mvn install -f terasoluna-gfw-functionaltest-domain/pom.xml
  - mvn install cargo:daemon-start -f terasoluna-gfw-functionaltest-web/pom.xml
  - mvn test -f terasoluna-gfw-functionaltest-selenium/pom.xml
